PRAGMA foreign_keys = ON;

-- Better Auth core schema generated by auth@1.6.26.
CREATE TABLE "user" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "email" TEXT NOT NULL UNIQUE,
  "emailVerified" INTEGER NOT NULL,
  "image" TEXT,
  "createdAt" DATE NOT NULL,
  "updatedAt" DATE NOT NULL
);

CREATE TABLE "session" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "expiresAt" DATE NOT NULL,
  "token" TEXT NOT NULL UNIQUE,
  "createdAt" DATE NOT NULL,
  "updatedAt" DATE NOT NULL,
  "ipAddress" TEXT,
  "userAgent" TEXT,
  "userId" TEXT NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE
);

CREATE TABLE "account" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "accountId" TEXT NOT NULL,
  "providerId" TEXT NOT NULL,
  "userId" TEXT NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE,
  "accessToken" TEXT,
  "refreshToken" TEXT,
  "idToken" TEXT,
  "accessTokenExpiresAt" DATE,
  "refreshTokenExpiresAt" DATE,
  "scope" TEXT,
  "password" TEXT,
  "createdAt" DATE NOT NULL,
  "updatedAt" DATE NOT NULL
);

CREATE TABLE "verification" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "identifier" TEXT NOT NULL,
  "value" TEXT NOT NULL,
  "expiresAt" DATE NOT NULL,
  "createdAt" DATE NOT NULL,
  "updatedAt" DATE NOT NULL
);

CREATE INDEX "session_userId_idx" ON "session" ("userId");
CREATE INDEX "account_userId_idx" ON "account" ("userId");
CREATE INDEX "verification_identifier_idx" ON "verification" ("identifier");

-- Application-owned account settings. Gemini credentials are encrypted before
-- they reach this table; only the final four characters are stored as a hint.
CREATE TABLE user_settings (
  user_id TEXT NOT NULL PRIMARY KEY
    REFERENCES "user" (id) ON DELETE CASCADE,
  model TEXT NOT NULL DEFAULT 'gemini-2.5-flash'
    CHECK (model IN ('gemini-2.5-flash', 'gemini-2.5-pro')),
  encrypted_api_key TEXT,
  api_key_iv TEXT,
  api_key_hint TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  CHECK (
    (encrypted_api_key IS NULL AND api_key_iv IS NULL AND api_key_hint IS NULL)
    OR
    (encrypted_api_key IS NOT NULL AND api_key_iv IS NOT NULL AND api_key_hint IS NOT NULL)
  )
);

CREATE TABLE workspace_preferences (
  user_id TEXT NOT NULL PRIMARY KEY
    REFERENCES "user" (id) ON DELETE CASCADE,
  active_document_id TEXT,
  reader_font_family TEXT NOT NULL DEFAULT 'serif'
    CHECK (reader_font_family IN ('serif', 'sans', 'mono')),
  close_reading_font_family TEXT NOT NULL DEFAULT 'sans'
    CHECK (close_reading_font_family IN ('serif', 'sans', 'mono')),
  reader_font_size REAL NOT NULL DEFAULT 18,
  reader_line_spacing REAL NOT NULL DEFAULT 1.75,
  analysis_language TEXT NOT NULL DEFAULT 'en'
    CHECK (analysis_language IN ('zh', 'en', 'fr', 'de', 'es', 'it', 'ja')),
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);

-- A reading session is the durable form of the frontend WorkspaceDocument.
CREATE TABLE reading_session (
  id TEXT NOT NULL PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES "user" (id) ON DELETE CASCADE,
  title TEXT NOT NULL CHECK (length(title) BETWEEN 1 AND 160),
  source_text TEXT NOT NULL,
  source_type TEXT NOT NULL
    CHECK (source_type IN ('paste', 'file', 'history')),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  last_opened_at TEXT,
  active_anchor_id TEXT,
  revision INTEGER NOT NULL DEFAULT 1,
  synced_at INTEGER NOT NULL
);

CREATE INDEX reading_session_user_recency_idx
  ON reading_session (user_id, last_opened_at, updated_at);

-- Anchors preserve exact source positions for selected passages and close reads.
CREATE TABLE reading_anchor (
  id TEXT NOT NULL PRIMARY KEY,
  session_id TEXT NOT NULL
    REFERENCES reading_session (id) ON DELETE CASCADE,
  scope TEXT NOT NULL CHECK (scope IN ('document', 'paragraph', 'selection')),
  quote TEXT NOT NULL,
  normalized_quote TEXT NOT NULL,
  quote_hash TEXT NOT NULL,
  start_offset INTEGER NOT NULL CHECK (start_offset >= 0),
  end_offset INTEGER NOT NULL CHECK (end_offset > start_offset),
  created_at TEXT NOT NULL,
  position INTEGER NOT NULL
);

CREATE INDEX reading_anchor_session_position_idx
  ON reading_anchor (session_id, position);

-- Artifacts cover notes and every AI-produced entry linked to an anchor.
CREATE TABLE reading_artifact (
  id TEXT NOT NULL PRIMARY KEY,
  session_id TEXT NOT NULL
    REFERENCES reading_session (id) ON DELETE CASCADE,
  anchor_id TEXT NOT NULL
    REFERENCES reading_anchor (id) ON DELETE CASCADE,
  type TEXT NOT NULL
    CHECK (type IN ('note', 'explanation', 'translation', 'vocabulary', 'close_read')),
  title TEXT NOT NULL CHECK (length(title) BETWEEN 1 AND 160),
  content TEXT NOT NULL,
  status TEXT NOT NULL
    CHECK (status IN ('draft', 'running', 'stopped', 'failed', 'complete')),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  request_id TEXT,
  trace_id TEXT,
  error_message TEXT,
  position INTEGER NOT NULL
);

CREATE INDEX reading_artifact_session_position_idx
  ON reading_artifact (session_id, position);
CREATE INDEX reading_artifact_anchor_idx
  ON reading_artifact (anchor_id);
